# Incerteza, risco e utilidade esperada

Raramente nossas decisões não estão envoltas em incertezas. Considere o problema de decisão do eleitorado. É preciso avaliar as alternativas disponíveis, esperando um certo resultado, que é incerto. Políticos não cumprem promessas, circunstâncias mudam, pessoas morrem e seus vices assumem etc.

Similarmente, imagine uma gestora pública municipal que foi apresentada a uma nova pesquisa, que sugere que é melhor que crianças entrem na escola uma hora mais tarde. Porém, isso mudará a organização dos cuidadores das crianças, professores e toda a dinâmica escolar, além do que o estudo foi feito em poucas escolas, não necessariamente se generalizando para todo o município. decidindo se adotar uma nova política pública ou continua com a anterior. Será que vale a pena esta nova política pública? Como é uma política nova, há incerteza sobre os benefícios que podem advir dela, bem como dificuldades não antecipadas inteiramente. Portanto, nosso modelo de tomada de decisão precisa incorporar incerteza de algum modo.

Em nosso paradigma da escolha racional, precisamos formalizar a incerteza para além de uma linguagem vaga como é possível, pode ou não acontecer, talvez... Vamos então introduzir um modo pelo qual jogadoras podem comparar ações cujos resultados são incertos de uma maneira estruturada e formalizável. Nesta abordagem, utilizaremos resultados aleatórios e, portanto, o conceito de probabilidades, de forma a definir *payoffs* sobre resultados aleatórios.

## Risco

Imagine que você é a gestora pública. Vamos formalizar o problema que ela enfrenta da forma mais simples possível, de modo a introduzir as ideias mais importantes de como modelar incerteza. Vamos chamar suas duas possíveis ações, inovar, $i$ e manter o status quo, $s$, de forma que o conjunto de ações é $A = \{i,s\}$. Vamos supor também que só há dois resultados possíveis: um benefício de $10$ (digamos, a nota na avaliação municipal é dez pontos maior) ou de $0$, de modo que $X = \{0,10\}$.

Entretanto, diferentemente de um mundo sem incerteza, não há correspondência unívoca entre ações e resultados. Para formalizar a ideia de incerteza aqui, precisamos atribuir probabilidades aos resultados em função de cada ação escolhida. Nesse exemplo fictício, as probabilidades são arbitrárias. Voltaremos a como determinar probabilidades mais à frente.

Suponha que se ela escolher adotar a nova política tem chance resultar em aumento de 10 pontos de 3 para 1, enquanto se não adotar a política e manter as coisas como estão, a chance é de 50%-50%. Dizendo de outro modo, a ação $i$ gera benefício $10$ com probabilidade $1/4$ e benefício $0$ com probabilidade $3/4$, enquanto a ação $s$ gera benefício $10$ com probabilidade $1/2$ e benefício $0$ com a mesma probabilidade.

A introdução de probabilidades traz incerteza para nossos jogos. Por isso é importante entender como nossa teortia de comportamento racional pode se modificar na presença de incerteza.

## Incerteza

A ideia da incerteza foi inicialmente abordada com a ideia de calcular o valor esperado de ações e escolher aquela ação que rende o maior valor esperado. Considere o seguinte jogo. Após responder várias perguntas corretas, uma pessoa em um programa de TV tem a seguinte escolha para fazer:
 a) será jogada uma moeda. Se cair coroa, ganha 100 mil reais. Se der cara, não ganha nada.
 b) Escolher entre três envelopes, cada um contém prêmios no valor de 90 mil reais, 30 mil reais e 15 mil reais. Qual estratégia ele deve escollher?
 
 O valor esperado de cada ação pode ser calculado da seguinte forma:
 a) $VE(A) = 100000*.5 + 0*.5 = 50.000,00$
 b) $VE(B) = 90000*(1/3) + 30000*(1/3) + 15000*(1/3) = 30000 + 10000 + 5000 = 45000$
 A pessoa deveria, portanto, escolher A, pois em média paga mais que do que a opção B.
 Uma justificativa para a ideia de maximizar o valor esperado é a seguinte. A pessoa se defronta com várias decisões em sua vida que possuem riscos. Pode comprar um carro com algum opcional de segurança que reduz seu risco de vida em acidentes, se vai atravessar fora da faixa e pedestre, se anda de moto, se sai na chuva em dia de raios etc. Cada decisão dela tem um risco e se escolher sempre maximizando a utilidade esperada, na média de longo prazo terá um retorno maior.
 
Um problema da abordagem de maximizar o valor esperado é ilustrado pelo Paradoxo de São Petersburgo. Considere o seguinte jogo. Uma moeda é jogada, se o resultado é coroa, o jogador é pago 1 real e o jogo acaba. Se der cara, o jogo continua e uma moeda é novamente lançada. Se der coroa, recebe dois reais e o jogo acaba. Se der cara, o jogo continua e uma moeda é novamente lançada. Se der coroa, o jogador ganha 4 reais e o jogo acaba. Se der cara, o jogo continua, e assim indefinidamente, sempre dobrando o valor pago até o momento em que der cara.
 
Suponha que a casa tem fundos ilimitados. Qual o valor esperado desse jogo? Ou, colocando de outro modo, quanto um jogador racional (no sentido de maximizar valor esperado) deveria pagar para ter o privilégio de jogar esse jogo?
O jogo basicamente tem a seguinte configuração. A casa paga 1 real com probabiliade 50%, 2 reais com probabilidade 25%, 4 reais com prob. 1/8 e assim por diante:
 $VE(jogo) = 1*(1/2) + 2*(1/4) + 4*(1/8) + ...$
 
 Veja que essa soma infinita é equivalente a:
 
  $VE(jogo) = 1/2 + 2*/4 + 4/8 + ... = 1/2 + 1/2 + 1/2 + ...$

O que dá uma soma infinita.

Usando nossa lógica de escolher ações cujo valor esperado é maior, entre a alternativa de pagar toda a fortuna de uma pessoa para jogar o jogo e não jogar e preservar a forturna, pagar a fortuna dá um valor esperado maior, pois infinito menos uma quantia finita é ainda infinito.

Obviamente, não faz sentido escolher jogar esse jogo pagando toda a sua fortuna, pois na prática em algum momento a pessoa irá perder antes de recuperar o valor de sua forturna.

Naturalmente, a questão seguinte a se perguntar é: podemos encontrar algum outro princípio para fundamentar a decisão sob incerteza?

Daniel Bernoulli, matemático, percebeu que o valor monetário é diferente a depender de quanto dinheiro você tem. O valor de mil reais para uma pessoa pobre é diferente do valor de mil reais para uma pessoa rica. Obviamente podemos supor que mais dinheiro é preferido a menos, porém não de maneira linear. Bernoulli sugeriu uma "lei da utilidade decrescente", como ficou conhecida depois, segundo a qual cada real adicional gera um pouco menos de utilidade. Mais ainda, ele propôs que a relação entre dinheiro e utilidade deveria ser logarítmica, o que implica que mudanças percentuais no dinheiro implicam mudanças iguais na utilidade.

Duas críticas forma feitas à proposta de Bernoulli. Em primeiro lugar, a arbitrariedade do uso de logarítmo. Em segundo lugar, como medir utilidades? Nós já vimos que podemos trabalhar com utilidades ordinais. Mas cardinais, é bem mais complicado.

Tivemos de esperar até o trabalho de von Neumann e Morgenstern (VNM), com o livro Game Theory and Economic Behavior (1944) para haver uma reabilitação das ideias propostas por Bernoulli. A ideia chave de VNM é que é possível estimar a intensidade de preferências em uma escala intervalar (em que os pontos máximos e mínimos são arbitŕarios, como na escala de celcius e farenheit) a partir da elicitação de preferências sobre loterias. Com representações numéricas de utilidade, podemos calcular a utilidade esperada (à maneira do valor esperado), exceto que a utilidade marginal pode ser decrescente e, portanto, evitar o paradoxo de São Petersburgo.

Vamos ver como funciona por meio do seguinte exemplo.

Suponha que uma loteria tem quatro possíveis prêmios: $x_1, x_2, x_3, x_4$. Suponha que os prêmios foram ordenados em ordem ascendente de preferência, isto é, $x_4 \succ x_3 \succ x_2 \succ x_1$. Agora, atribua valores de utilidade arbitrários para o prêmio mais desejado e o menos desejado. Digamos: $u(x_4) = 1$ e $u(x_1) = 0$.

Quaisquer outros números funcionariam, mas é conveniente matematicamente (já veremos o porquê) usar zero e um. Usando esses dois valores de utilidade como ancoragem, o ponto do teorema de VNM é que existe uma forma garantida de atribuir utilidades numéricas para as preferências de cada um dos prêmios, de forma que podemos trabalhar com o caĺculo de utilidade esperada. O procedimento é o seguinte. Considere qualquer outro prêmio (por exemplo, $x_2$). Pergutamos então a cada jogador qual a probabilidade $p_2$ que tornaria ela indiferente entre ganhar $x_2$ com certeza e $x_4$ com probabilidade $p_2$ e $x_1$ com probabilidade $1 - p_2$. Veja que quanto mais valioso for $x_2$, maior deve ser $p_2$, a chance de ganhar $x_4$ o prêmio mais valorizado, para que a pessoa aceite trocar algo certo por aldo duvidoso. Assim, $p_2$ mede a desejabilidade do prêmio $x_2$.
A gente repete esse experimento com $x_3$ e assim teremos uma medida da desejabilidade de todos os prêmios.

E VNM definem a utilidade de cada prêmio como a aposta (loteria)que cada jogador considera igualmente desejável ao prêmio:

$u(x_i) = p_i*x_n + (1-p_i)*x_1$
No no caso:
$u(x_i) = p_i*1 + (1-p_i)*0 = p_i$

Ao escolher os valores máximos e mínimos da utilidade de maneira conveniente, as probabilidades passam a medir a desejabilidade diretamente de cada prêmio. Temos portanto números para as utilidades que não são apenas ordinais, mas cardinais.

Eu sei que nós gastamos muito tempo repetindo e enfatizando que a teoria da utilidade tratava apenas de representar preferências ordinais e, portanto, os números eram completamente arbitrários. Agora não. Somente os pontos máximos e mínimos são arbitrários, mas todos os demais são derivados por esse experimento mental. 

Na verdade, para ser mais preciso, o que VNM mostram é que se alguns axiomas forem satisfeitos, então agentes racionais se comportatão como se tivessem respondido a essas perguntas desse experimento. Mas não precisam de fato fazer esse experimento para se comportarem desse jeito. Mais ainda, em situações de incerteza, agentes racionais escolherão o que maximizar sua utilidade esperada.

A Teoria da Utilidade Esperada, portanto, ajuda a explicar porque pessoas contratam seguros ou apostam em loterias como a mega-sena. Embora o valor esperado seja negativo de ambas as escolhas, as pessoas possuem utilidades distintas de cada opção (jogar ou não jogar, contratar ou não-contratar seguro).

## Risco versos Incerteza

Até aqui não temos feito diferenciação entre incerteza e risco. Contudo, nas ciências sociais, muita discussão foi feita ao longo do século XX sobre a diferença entre esses dois conceitos. O economia John Manard Keynes, por exemplo, defendia que risco eram aquelas situações nas quais podemos calcular uma probabilidade objetiva, enquanto incerteza seriam situações em que não poderíamos atribuir uma probabilidade. Exemplo de risco seria uma probabilidade de chover, que pode impactar os rendimentos de um evento (um show a ceu aberto) ou negócio (um bar na praia), enquanto incerteza envolveria coisas como uma decisão de investir em um novo negócio, ou a possibilidade de uma pandemia mundial.

A diferença entre os dois conceitos parece ter sido introduzida pela primeira vez pelo economista Frank Knight, que escreveu em 1921:

Uncertainty must be taken in a sense radically distinct from the familiar notion of risk, from which it has never been properly separated.... The essential fact is that 'risk' means in some cases a quantity susceptible of measurement, while at other times it is something distinctly not of this character; and there are far-reaching and crucial differences in the bearings of the phenomena depending on which of the two is really present and operating.... It will appear that a
measurable uncertainty, or 'risk' proper, as we shall use the term, is so far different from an unmeasurable one
that it is not in effect an uncertainty at all".

Em resumo, incerteza é quando eventos futuros ou resultados de ações não poderiam ter uma probabilidade associada, enquanto risco seriam situações opostas, ou seja, quando é possível atribuir uma probabilidade.

Do ponto de vista da abordagem Bayesiana, que implicitamente é utilizada em nosso curso, tal diferença não faz sentido. Toda situação de incerteza pode ser modelada como uma probabilidade, ainda que subjetiva, isto é, baseada apenas em um mero chute.

## Aversão a risco

Tipicamente as pessoas são avessas ao risco. No contexto da utilidade esperada, isso quer dizer que as pessoas preferem um payoff certo a uma aposta justa. Em outras palavras, se eu oferecer uma escolha entre ficar como está ou uma aposta em que você ganha mil reais se der cara, paga mil reais se der coroa, as pessoas tendem a preferir a primeira opção, ainda que o valor esperado seja igual. Se vocÇe for indiferente entre as duas opções, dizemos que você é neutro ao risco. E se prefere a aposta, você é amante do risco.

Tipicamente em modelos na ciência política, assume-se neutralidade ao risco ou aversão ao risco. Aversão ao risco é visto como a suposição mais aceitável e neutralidade ao risco é suposta apenas quando é mais fácil a matemática e a conclusão não muda se supusermos aversão ao risco.

## Teoria e Prática

Muitos testes foram feitos para verificar se o comportameto das pessoas em situações experimentais condizem com o previsto pela TUE. Em particular, Tversky and Kanheman realizaram uma série de experimentos. Vamos apresentar um deles aqui.

"Suponha que o Brasil está se preparando para um surto de uma doença que surgiu em outro país e a expectativa é que a doença matará 600 pessoas se nada for feito. Dois programas alternativos para combater as doenças foram pensados. Assuma que as exatas consequências científicas dos programas são como seguem:

1. 
Programa A: 200 pessoas serão salvas.
Programa B: Há uma probabilidade de $1/3$ que 600 pessoas serão salvas, e uma probabilidade de $2/3$ que nenhuma pessoa será salva.


72% escolherão A e 28% B
2. 
Programa C: 400 pessoas morrerão.
Programa D: Há uma probabilidade de $1/3$ que ninguém morrerá, e uma probabilidade de $2/3$ que 600 pessoas morrerão.

Já nesse cenário, 78% preferem D e 22% preferem C.

## Preferências sobre loterias

Já que estamos falando de loterias em nossa definição, é importante fazer um detour para explicar o conceito de loterias e preferências sobre loterias

Uma loteria existe quando eu tenho payoffs que têm um componente aleatório. A mega-sena paga alguns milhões de reais com uma dada probabilidade, e zero reais com outra probabilidade.

Mais formalmente:
Definição 6.2. Uma loteria simples sobre resultados $X = {x_1, x_2, ..., x_n}$ é definida como a distribuição de probabilidade $p = (p(x_1), p(x_2), ..., p(x_n))$, em que $p(x_k) \ge 0$ é a probabilidade de que $x_k$ ocorra e $\Sigma_{k=1}^n x_k = 1$.

## Referências

Knight, F. H., 1921. Risk, uncertainty and profit. University of Chicago Press.